apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-java-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-java
  template:
    metadata:
      labels:
        app: hello-java
    spec:
      containers:
      - name: hello-java
        image: <your-docker-image>:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
